"""
InbXr Signal Report PDF Generator
──────────────────────────────────
Generates a branded PDF report of a user's current Signal Score and the
7 Inbox Signals breakdown. Used by:

- /signal-score/pdf    User-triggered download from the dashboard
- Weekly report emails (future — PDF attachment mode)
- Admin tools (future — generate sample PDFs for sales)

Three variants branching on tier:

    free    One-page summary. Signal Score + grade + 7 signal bars +
            top 3 recommendations. InbXr branding always visible.

    pro     Multi-page report. Everything in free, plus a 14-day history
            sparkline per signal, trajectory indicators, and a segments
            breakdown page. InbXr branding.

    agency  Same structure as pro, but renders the user's uploaded logo,
            primary color, and footer text. Can optionally hide the
            "Generated by InbXr Signal Engine" line entirely.

The generator is programmatic (ReportLab) rather than HTML-to-PDF so we
get precise layout control, small file sizes, and fast generation with
zero system dependencies. Pure Python. Deploys cleanly on Railway.
"""

import io
import json
import logging
import os
from datetime import datetime

from reportlab.lib import colors
from reportlab.lib.colors import HexColor
from reportlab.lib.enums import TA_CENTER, TA_LEFT, TA_RIGHT
from reportlab.lib.pagesizes import LETTER
from reportlab.lib.styles import ParagraphStyle, getSampleStyleSheet
from reportlab.lib.units import inch
from reportlab.pdfgen import canvas
from reportlab.platypus import (
    Paragraph, SimpleDocTemplate, Spacer, Table, TableStyle, PageBreak,
    KeepTogether,
)

from modules.database import fetchone, fetchall, execute
from modules.signal_copy import (
    SIGNAL_DIMENSION_COPY,
    SIGNAL_GRADE_COPY,
    ACTION_RECOMMENDATIONS,
)
from modules.tiers import has_feature

logger = logging.getLogger(__name__)


# ── Color system ────────────────────────────────────────
#
# The PDF uses a restrained palette so white-label overrides (agency tier)
# can swap the accent color without breaking the layout. Grayscale is
# always neutral; only the accent hex changes between variants.

DEFAULT_BRAND = "#2563eb"
BRAND_DARK = "#1e40af"
INK = "#0f172a"
INK_SOFT = "#334155"
INK_MUTE = "#64748b"
INK_FAINT = "#94a3b8"
PAPER = "#ffffff"
PAPER_ALT = "#f8fafc"
RULE = "#e2e8f0"
GRADE_COLORS = {
    "A": "#059669",
    "B": "#0891b2",
    "C": "#d97706",
    "D": "#dc2626",
    "F": "#991b1b",
}


# Signal display order (canonical)
SIGNAL_ORDER = [
    "bounce_exposure",
    "engagement_trajectory",
    "acquisition_quality",
    "domain_reputation",
    "dormancy_risk",
    "authentication_standing",
    "decay_velocity",
]

SIGNAL_MAX_POINTS = {
    "bounce_exposure": 25,
    "engagement_trajectory": 25,
    "acquisition_quality": 15,
    "domain_reputation": 15,
    "dormancy_risk": 10,
    "authentication_standing": 5,
    "decay_velocity": 5,
}


# ── Data loading ────────────────────────────────────────


def _load_user(user_id):
    """Load user row including agency white-label settings."""
    return fetchone(
        "SELECT id, email, display_name, tier, "
        "agency_logo_url, agency_primary_color, agency_footer_text, "
        "agency_hide_inbxr_brand "
        "FROM users WHERE id = ?",
        (user_id,),
    )


def _load_latest_score(user_id, score_id=None):
    """Load the score row the report will render. If score_id is given,
    load that specific row (used by shared links). Otherwise load the
    most recent score for the user."""
    if score_id:
        return fetchone(
            "SELECT * FROM signal_scores WHERE id = ? AND user_id = ?",
            (score_id, user_id),
        )
    return fetchone(
        "SELECT * FROM signal_scores WHERE user_id = ? "
        "ORDER BY calculated_at DESC LIMIT 1",
        (user_id,),
    )


def _load_history(user_id, limit=14):
    """Last N days of signal history. Used by Pro/Agency variants for
    sparklines and the 14-day trend comparison. Returns oldest-first
    so the sparkline draws left to right."""
    rows = fetchall(
        "SELECT total_signal_score, bounce_exposure_score, "
        "engagement_trajectory_score, acquisition_quality_score, "
        "domain_reputation_score, dormancy_risk_score, "
        "authentication_standing_score, decay_velocity_score, "
        "recorded_at "
        "FROM signal_score_history WHERE user_id = ? "
        "ORDER BY recorded_at DESC LIMIT ?",
        (user_id, limit),
    )
    return list(reversed(rows)) if rows else []


def _weakest_signal(score_row):
    """Identify the weakest signal by percentage of its weight."""
    ratios = []
    for key in SIGNAL_ORDER:
        max_pts = SIGNAL_MAX_POINTS[key]
        value = score_row.get(f"{key}_score") or 0
        ratios.append((key, value / max_pts if max_pts else 0))
    ratios.sort(key=lambda x: x[1])
    return ratios[0][0] if ratios else None


def _resolve_variant(user, score_row):
    """Pick which PDF variant to render for this user.

    Agency users get the white-label variant IF they have intelligence
    access. Pro users get history charts. Free users get the basic
    one-page report. Honors the tier override from the score row so
    old scores keep their original tier framing."""
    tier = user.get("tier", "free")
    if tier == "agency" and has_feature(tier, "signal_pdf_white_label"):
        return "agency"
    if has_feature(tier, "signal_pdf_history"):
        return "pro"
    return "free"


def _brand_color_for(user, variant):
    """Return the accent HexColor for this user's variant. Agency users
    with a custom primary color override the default brand blue. All
    other variants use the default."""
    if variant == "agency":
        custom = (user.get("agency_primary_color") or DEFAULT_BRAND).strip()
        if custom.startswith("#") and len(custom) in (4, 7):
            try:
                return HexColor(custom)
            except Exception:
                pass
    return HexColor(DEFAULT_BRAND)


# ── Paragraph style factory ─────────────────────────────


def _styles(accent_color):
    """Build a style dictionary keyed by logical name. Takes the accent
    color so white-label variants can swap it without forking the whole
    style block."""
    base = getSampleStyleSheet()
    return {
        "title": ParagraphStyle(
            "title",
            parent=base["Title"],
            fontName="Helvetica-Bold",
            fontSize=26,
            leading=30,
            textColor=HexColor(INK),
            spaceAfter=6,
            alignment=TA_LEFT,
        ),
        "subtitle": ParagraphStyle(
            "subtitle",
            parent=base["Normal"],
            fontName="Helvetica",
            fontSize=11,
            leading=14,
            textColor=HexColor(INK_MUTE),
            spaceAfter=14,
            alignment=TA_LEFT,
        ),
        "eyebrow": ParagraphStyle(
            "eyebrow",
            parent=base["Normal"],
            fontName="Helvetica-Bold",
            fontSize=8,
            leading=10,
            textColor=accent_color,
            spaceAfter=6,
            alignment=TA_LEFT,
        ),
        "section_h": ParagraphStyle(
            "section_h",
            parent=base["Heading2"],
            fontName="Helvetica-Bold",
            fontSize=14,
            leading=18,
            textColor=HexColor(INK),
            spaceAfter=8,
            spaceBefore=16,
            alignment=TA_LEFT,
        ),
        "body": ParagraphStyle(
            "body",
            parent=base["Normal"],
            fontName="Helvetica",
            fontSize=10,
            leading=14,
            textColor=HexColor(INK_SOFT),
            spaceAfter=8,
            alignment=TA_LEFT,
        ),
        "body_small": ParagraphStyle(
            "body_small",
            parent=base["Normal"],
            fontName="Helvetica",
            fontSize=8.5,
            leading=12,
            textColor=HexColor(INK_MUTE),
            spaceAfter=6,
            alignment=TA_LEFT,
        ),
        "signal_name": ParagraphStyle(
            "signal_name",
            parent=base["Normal"],
            fontName="Helvetica-Bold",
            fontSize=11,
            leading=14,
            textColor=HexColor(INK),
            alignment=TA_LEFT,
        ),
        "signal_weight": ParagraphStyle(
            "signal_weight",
            parent=base["Normal"],
            fontName="Helvetica",
            fontSize=8,
            leading=10,
            textColor=HexColor(INK_FAINT),
            alignment=TA_RIGHT,
        ),
        "signal_note": ParagraphStyle(
            "signal_note",
            parent=base["Normal"],
            fontName="Helvetica-Oblique",
            fontSize=8,
            leading=11,
            textColor=HexColor(INK_MUTE),
            alignment=TA_LEFT,
            spaceAfter=4,
        ),
        "signal_what": ParagraphStyle(
            "signal_what",
            parent=base["Normal"],
            fontName="Helvetica",
            fontSize=8,
            leading=11,
            textColor=HexColor(INK_MUTE),
            alignment=TA_LEFT,
        ),
        "grade_giant": ParagraphStyle(
            "grade_giant",
            parent=base["Title"],
            fontName="Helvetica-Bold",
            fontSize=72,
            leading=76,
            textColor=HexColor(INK),
            alignment=TA_CENTER,
        ),
        "grade_label": ParagraphStyle(
            "grade_label",
            parent=base["Normal"],
            fontName="Helvetica-Bold",
            fontSize=11,
            leading=14,
            textColor=HexColor(INK_MUTE),
            alignment=TA_CENTER,
            spaceAfter=4,
        ),
    }


# ── Drawing helpers ─────────────────────────────────────


def _draw_progress_bar(canvas_obj, x, y, width, height, filled_ratio, accent):
    """Draw a rounded progress bar. Used for each signal score."""
    filled_ratio = max(0, min(1, filled_ratio))
    # Track
    canvas_obj.setFillColor(HexColor(RULE))
    canvas_obj.roundRect(x, y, width, height, height / 2, stroke=0, fill=1)
    # Fill
    if filled_ratio > 0:
        fill_width = max(height, width * filled_ratio)
        canvas_obj.setFillColor(accent)
        canvas_obj.roundRect(x, y, fill_width, height, height / 2, stroke=0, fill=1)


def _draw_sparkline(canvas_obj, x, y, width, height, values, accent):
    """Draw a mini sparkline chart from a list of numeric values.
    Used on Pro/Agency variants for the 14-day history per signal.
    Silently renders nothing if there are fewer than 2 data points."""
    if not values or len(values) < 2:
        # Draw a baseline only
        canvas_obj.setStrokeColor(HexColor(RULE))
        canvas_obj.setLineWidth(0.5)
        canvas_obj.line(x, y + height / 2, x + width, y + height / 2)
        return

    clean = [v for v in values if v is not None]
    if len(clean) < 2:
        canvas_obj.setStrokeColor(HexColor(RULE))
        canvas_obj.line(x, y + height / 2, x + width, y + height / 2)
        return

    v_min = min(clean)
    v_max = max(clean)
    v_range = v_max - v_min if v_max > v_min else 1

    # Scale x across count-1 segments
    n = len(values)
    x_step = width / (n - 1)

    # Build line path
    points = []
    for i, v in enumerate(values):
        if v is None:
            continue
        px = x + i * x_step
        py = y + ((v - v_min) / v_range) * height
        points.append((px, py))

    canvas_obj.setStrokeColor(accent)
    canvas_obj.setLineWidth(1.2)
    canvas_obj.setLineCap(1)
    canvas_obj.setLineJoin(1)
    for i in range(len(points) - 1):
        canvas_obj.line(points[i][0], points[i][1], points[i + 1][0], points[i + 1][1])

    # End dot
    if points:
        canvas_obj.setFillColor(accent)
        canvas_obj.circle(points[-1][0], points[-1][1], 1.5, stroke=0, fill=1)


def _draw_score_card(canvas_obj, doc, score_value, grade, accent):
    """Top-of-page-1 hero block with the big score and grade. Drawn as
    a canvas overlay so we get control over absolute position instead
    of being at the mercy of flowable layout."""
    page_width = LETTER[0]
    left = doc.leftMargin
    right = page_width - doc.rightMargin
    width = right - left
    top = LETTER[1] - 1.5 * inch

    # Card background
    card_h = 1.6 * inch
    card_y = top - card_h
    canvas_obj.setFillColor(HexColor(PAPER_ALT))
    canvas_obj.setStrokeColor(HexColor(RULE))
    canvas_obj.setLineWidth(0.75)
    canvas_obj.roundRect(left, card_y, width, card_h, 12, stroke=1, fill=1)

    # Giant score on the left
    canvas_obj.setFillColor(HexColor(INK))
    canvas_obj.setFont("Helvetica-Bold", 64)
    score_text = f"{int(round(score_value))}"
    score_text_width = canvas_obj.stringWidth(score_text, "Helvetica-Bold", 64)
    score_x = left + 0.5 * inch
    score_y = card_y + 0.35 * inch
    canvas_obj.drawString(score_x, score_y, score_text)

    # " / 100" suffix
    canvas_obj.setFont("Helvetica", 16)
    canvas_obj.setFillColor(HexColor(INK_FAINT))
    canvas_obj.drawString(score_x + score_text_width + 6, score_y + 4, "/ 100")

    # "Signal Score" label under the score
    canvas_obj.setFont("Helvetica-Bold", 8)
    canvas_obj.setFillColor(HexColor(INK_MUTE))
    canvas_obj.drawString(score_x, card_y + 0.18 * inch, "SIGNAL SCORE")

    # Grade pill on the right
    grade_color = HexColor(GRADE_COLORS.get(grade, INK))
    pill_w = 1.1 * inch
    pill_h = 0.7 * inch
    pill_x = right - pill_w - 0.5 * inch
    pill_y = card_y + (card_h - pill_h) / 2
    canvas_obj.setFillColor(grade_color)
    canvas_obj.roundRect(pill_x, pill_y, pill_w, pill_h, 10, stroke=0, fill=1)
    canvas_obj.setFillColor(HexColor("#ffffff"))
    canvas_obj.setFont("Helvetica-Bold", 32)
    grade_text_w = canvas_obj.stringWidth(grade, "Helvetica-Bold", 32)
    canvas_obj.drawString(pill_x + (pill_w - grade_text_w) / 2, pill_y + 0.18 * inch, grade)
    canvas_obj.setFont("Helvetica-Bold", 7)
    canvas_obj.drawString(pill_x + 0.12 * inch, pill_y - 0.16 * inch, "GRADE")

    # Grade label between score and pill
    label_copy = SIGNAL_GRADE_COPY.get(grade, {})
    label = label_copy.get("label", "")
    if label:
        canvas_obj.setFillColor(HexColor(INK_MUTE))
        canvas_obj.setFont("Helvetica", 10)
        canvas_obj.drawString(score_x, card_y + 0.02 * inch - 6, label)


# ── Header and footer rendering ─────────────────────────


def _draw_header_footer(canvas_obj, doc, user, variant, accent, score_row):
    """Page decorator. Draws the brand strip at the top and the footer
    line at the bottom on every page. Agency variant uses the uploaded
    logo text (no raster image rendering yet — v1 defers that) and can
    hide the InbXr attribution."""
    canvas_obj.saveState()
    page_width = LETTER[0]
    page_height = LETTER[1]

    # ── Top brand strip ──
    strip_y = page_height - 0.45 * inch
    canvas_obj.setFillColor(accent)
    canvas_obj.rect(0, strip_y, page_width, 0.08 * inch, stroke=0, fill=1)

    # Brand label (either InbXr or agency custom text)
    if variant == "agency":
        brand_label = (user.get("agency_footer_text") or "").strip() or user.get(
            "display_name"
        ) or "Signal Report"
    else:
        brand_label = "InbXr · Signal Report"

    canvas_obj.setFillColor(HexColor(INK))
    canvas_obj.setFont("Helvetica-Bold", 10)
    canvas_obj.drawString(doc.leftMargin, strip_y + 0.22 * inch, brand_label)

    # Date on the right
    generated = datetime.utcnow().strftime("%B %d, %Y")
    canvas_obj.setFont("Helvetica", 9)
    canvas_obj.setFillColor(HexColor(INK_MUTE))
    date_w = canvas_obj.stringWidth(generated, "Helvetica", 9)
    canvas_obj.drawString(page_width - doc.rightMargin - date_w, strip_y + 0.22 * inch, generated)

    # ── Bottom footer ──
    footer_y = 0.4 * inch

    canvas_obj.setStrokeColor(HexColor(RULE))
    canvas_obj.setLineWidth(0.5)
    canvas_obj.line(doc.leftMargin, footer_y + 0.18 * inch, page_width - doc.rightMargin, footer_y + 0.18 * inch)

    # Left side: "Generated by InbXr Signal Engine" unless hidden
    hide_brand = variant == "agency" and bool(user.get("agency_hide_inbxr_brand"))
    if not hide_brand:
        canvas_obj.setFont("Helvetica", 7.5)
        canvas_obj.setFillColor(HexColor(INK_FAINT))
        canvas_obj.drawString(
            doc.leftMargin,
            footer_y,
            "Generated by the Signal Engine  ·  https://inbxr.us",
        )

    # Right side: page number
    page_num = canvas_obj.getPageNumber()
    canvas_obj.setFont("Helvetica", 7.5)
    canvas_obj.setFillColor(HexColor(INK_FAINT))
    page_text = f"Page {page_num}"
    pw = canvas_obj.stringWidth(page_text, "Helvetica", 7.5)
    canvas_obj.drawString(page_width - doc.rightMargin - pw, footer_y, page_text)

    canvas_obj.restoreState()


# ── Story builders for each content section ────────────


def _build_hero_flowables(score_row, styles):
    """Build the top flowables that sit below the canvas-drawn score card.
    We leave vertical space for the card via a Spacer that matches its
    height + a small breathing gap."""
    grade = score_row.get("signal_grade", "F")
    grade_copy = SIGNAL_GRADE_COPY.get(grade, {})
    total = score_row.get("total_signal_score") or 0
    total_contacts = score_row.get("total_contacts") or 0

    story = []
    # Reserve space for the canvas-drawn score card
    story.append(Spacer(1, 1.7 * inch))
    story.append(Paragraph("SIGNAL SCORE SUMMARY", styles["eyebrow"]))

    headline = grade_copy.get("description", "")
    if headline:
        story.append(Paragraph(headline, styles["body"]))

    contacts_line = (
        f"<b>{total_contacts:,}</b> contacts scored through the Signal Engine. "
        f"Report generated from the most recent scan."
    )
    story.append(Paragraph(contacts_line, styles["body_small"]))
    return story


def _build_signals_table(score_row, styles, accent, include_sparklines, history):
    """Build the 7-signal breakdown as a single Table flowable.

    Each row has: signal number + name, weight, score fraction, progress bar.
    For Pro/Agency variants with history, we pass include_sparklines=True
    and render a small sparkline column.
    """
    rows = []

    # Header
    header_cells = [
        Paragraph("<b>Signal</b>", styles["body_small"]),
        Paragraph("<b>Weight</b>", styles["signal_weight"]),
        Paragraph("<b>Score</b>", styles["signal_weight"]),
        Paragraph("<b>Reading</b>", styles["body_small"]),
    ]
    if include_sparklines:
        header_cells.append(Paragraph("<b>14d</b>", styles["signal_weight"]))
    rows.append(header_cells)

    for key in SIGNAL_ORDER:
        meta = SIGNAL_DIMENSION_COPY.get(key, {})
        max_pts = SIGNAL_MAX_POINTS[key]
        value = score_row.get(f"{key}_score") or 0
        number = meta.get("number", "")
        name = meta.get("name", key)
        note = meta.get("note", "")

        name_cell = Paragraph(
            f"<b>{number} · {name}</b><br/><font size='7' color='{INK_MUTE}'>{note}</font>",
            styles["body_small"],
        )
        weight_cell = Paragraph(f"{max_pts} pts", styles["signal_weight"])
        score_cell = Paragraph(
            f"<b>{value:.1f}</b> <font color='{INK_FAINT}'>/ {max_pts}</font>",
            styles["signal_weight"],
        )

        bar_ratio = (value / max_pts) if max_pts else 0
        # Reading column: progress bar drawn as a custom flowable via a Table trick
        # We stash the ratio so the TableStyle canvas callback can paint it.
        reading_cell = _ProgressBarFlow(bar_ratio, accent)

        cells = [name_cell, weight_cell, score_cell, reading_cell]

        if include_sparklines:
            # Extract the corresponding history column
            hist_values = [h.get(f"{key}_score") for h in history] if history else []
            cells.append(_SparklineFlow(hist_values, accent))

        rows.append(cells)

    col_widths = [2.0 * inch, 0.55 * inch, 0.7 * inch, 2.7 * inch]
    if include_sparklines:
        col_widths = [1.75 * inch, 0.5 * inch, 0.65 * inch, 2.05 * inch, 1.0 * inch]

    table = Table(rows, colWidths=col_widths, repeatRows=1)
    table.setStyle(
        TableStyle([
            ("VALIGN", (0, 0), (-1, -1), "MIDDLE"),
            ("LINEBELOW", (0, 0), (-1, 0), 0.5, HexColor(RULE)),
            ("LINEBELOW", (0, 1), (-1, -2), 0.25, HexColor(RULE)),
            ("TOPPADDING", (0, 1), (-1, -1), 8),
            ("BOTTOMPADDING", (0, 1), (-1, -1), 8),
            ("LEFTPADDING", (0, 0), (-1, -1), 4),
            ("RIGHTPADDING", (0, 0), (-1, -1), 4),
        ])
    )
    return table


def _build_recommendations(score_row, styles, accent):
    """Top 3 recommendations based on the weakest signals."""
    # Rank signals by ratio
    ratios = []
    for key in SIGNAL_ORDER:
        max_pts = SIGNAL_MAX_POINTS[key]
        value = score_row.get(f"{key}_score") or 0
        ratios.append((key, value / max_pts if max_pts else 1))
    ratios.sort(key=lambda x: x[1])

    story = [
        Paragraph("RECOMMENDED ACTIONS", styles["eyebrow"]),
        Paragraph("Fix these three first", styles["section_h"]),
    ]

    for rank, (key, ratio) in enumerate(ratios[:3], start=1):
        meta = SIGNAL_DIMENSION_COPY.get(key, {})
        action = ACTION_RECOMMENDATIONS.get(key, {})
        name = meta.get("name", key)
        action_label = action.get("label", f"Investigate {name}")
        action_feature = action.get("feature", "")

        bullet = (
            f"<b>{rank}. {name}</b> &mdash; {action_label}"
            + (f" <font color='{INK_FAINT}'>({action_feature})</font>" if action_feature else "")
        )
        story.append(Paragraph(bullet, styles["body"]))

    return story


def _build_segments_page(score_row, styles):
    """Segment breakdown flowables — only shown on Pro/Agency."""
    active = score_row.get("active_contacts") or 0
    warm = score_row.get("warm_contacts") or 0
    at_risk = score_row.get("at_risk_contacts") or 0
    dormant = score_row.get("dormant_contacts") or 0
    total = max(score_row.get("total_contacts") or 0, 1)

    story = [
        PageBreak(),
        Paragraph("LIST SEGMENTATION", styles["eyebrow"]),
        Paragraph("How your contacts are distributed", styles["section_h"]),
        Paragraph(
            "Segment ages are measured from the most recent engagement signal "
            "(open, click, or reply). Dormant contacts have not engaged in 180+ days.",
            styles["body"],
        ),
    ]

    data = [
        [
            Paragraph("<b>Segment</b>", styles["body_small"]),
            Paragraph("<b>Contacts</b>", styles["signal_weight"]),
            Paragraph("<b>Share</b>", styles["signal_weight"]),
            Paragraph("<b>Definition</b>", styles["body_small"]),
        ],
        [
            Paragraph("<b>Active</b>", styles["body"]),
            Paragraph(f"{active:,}", styles["signal_weight"]),
            Paragraph(f"{active / total * 100:.1f}%", styles["signal_weight"]),
            Paragraph("Engaged within the last 30 days", styles["body_small"]),
        ],
        [
            Paragraph("<b>Warm</b>", styles["body"]),
            Paragraph(f"{warm:,}", styles["signal_weight"]),
            Paragraph(f"{warm / total * 100:.1f}%", styles["signal_weight"]),
            Paragraph("Engaged 31 to 90 days ago", styles["body_small"]),
        ],
        [
            Paragraph("<b>At Risk</b>", styles["body"]),
            Paragraph(f"{at_risk:,}", styles["signal_weight"]),
            Paragraph(f"{at_risk / total * 100:.1f}%", styles["signal_weight"]),
            Paragraph("Engaged 91 to 180 days ago", styles["body_small"]),
        ],
        [
            Paragraph("<b>Dormant</b>", styles["body"]),
            Paragraph(f"{dormant:,}", styles["signal_weight"]),
            Paragraph(f"{dormant / total * 100:.1f}%", styles["signal_weight"]),
            Paragraph("No engagement in 180+ days", styles["body_small"]),
        ],
    ]

    table = Table(
        data,
        colWidths=[1.3 * inch, 1.2 * inch, 0.9 * inch, 2.5 * inch],
        repeatRows=1,
    )
    table.setStyle(
        TableStyle([
            ("VALIGN", (0, 0), (-1, -1), "MIDDLE"),
            ("LINEBELOW", (0, 0), (-1, 0), 0.5, HexColor(RULE)),
            ("LINEBELOW", (0, 1), (-1, -2), 0.25, HexColor(RULE)),
            ("TOPPADDING", (0, 1), (-1, -1), 10),
            ("BOTTOMPADDING", (0, 1), (-1, -1), 10),
        ])
    )
    story.append(table)

    return story


# ── Custom Flowables ────────────────────────────────────


class _ProgressBarFlow:
    """A tiny flowable that draws a horizontal progress bar. We use a
    plain object instead of a true Flowable because ReportLab accepts
    anything that implements wrap() + drawOn() + getSpaceBefore/After."""

    def __init__(self, ratio, accent):
        self.ratio = ratio
        self.accent = accent
        self._width = 2.6 * inch
        self._height = 0.18 * inch

    def wrap(self, avail_w, avail_h):
        self._width = min(self._width, avail_w)
        return self._width, self._height

    def drawOn(self, canvas_obj, x, y, _sW=0):
        _draw_progress_bar(canvas_obj, x, y, self._width, self._height, self.ratio, self.accent)

    def getSpaceBefore(self):
        return 0

    def getSpaceAfter(self):
        return 0


class _SparklineFlow:
    """Sparkline flowable. Same interface contract as _ProgressBarFlow."""

    def __init__(self, values, accent):
        self.values = values
        self.accent = accent
        self._width = 0.95 * inch
        self._height = 0.3 * inch

    def wrap(self, avail_w, avail_h):
        self._width = min(self._width, avail_w)
        return self._width, self._height

    def drawOn(self, canvas_obj, x, y, _sW=0):
        _draw_sparkline(canvas_obj, x, y, self._width, self._height, self.values, self.accent)

    def getSpaceBefore(self):
        return 0

    def getSpaceAfter(self):
        return 0


# ── Top-level entry point ───────────────────────────────


def generate_pdf(user_id, score_id=None, variant=None):
    """Build a Signal Report PDF for a user.

    Returns (bytes, metadata_dict) on success, or (None, error_dict) on
    failure. The metadata dict includes variant, score, grade, and
    byte count so the caller can log the generation and enforce rate
    limits against the pdf_generations table.
    """
    user = _load_user(user_id)
    if not user:
        return None, {"error": "user_not_found"}

    score_row = _load_latest_score(user_id, score_id)
    if not score_row:
        return None, {"error": "no_score_yet"}

    # Resolve variant
    if variant is None:
        variant = _resolve_variant(user, score_row)

    accent = _brand_color_for(user, variant)
    styles = _styles(accent)

    history = []
    if variant in ("pro", "agency"):
        history = _load_history(user_id, limit=14)

    # Build the story
    story = []
    story.extend(_build_hero_flowables(score_row, styles))
    story.append(Paragraph("THE 7 INBOX SIGNALS", styles["eyebrow"]))
    story.append(Paragraph("Signal breakdown", styles["section_h"]))
    story.append(
        _build_signals_table(
            score_row,
            styles,
            accent,
            include_sparklines=(variant in ("pro", "agency")),
            history=history,
        )
    )
    story.append(Spacer(1, 0.2 * inch))
    story.extend(_build_recommendations(score_row, styles, accent))

    if variant in ("pro", "agency"):
        story.extend(_build_segments_page(score_row, styles))

    # Build the PDF
    buffer = io.BytesIO()
    doc = SimpleDocTemplate(
        buffer,
        pagesize=LETTER,
        leftMargin=0.65 * inch,
        rightMargin=0.65 * inch,
        topMargin=1.0 * inch,
        bottomMargin=0.8 * inch,
        title=f"Signal Report",
        author="InbXr",
    )

    grade = score_row.get("signal_grade", "F")
    score_value = score_row.get("total_signal_score") or 0

    def _on_page(canvas_obj, doc_ref):
        _draw_header_footer(canvas_obj, doc_ref, user, variant, accent, score_row)
        if canvas_obj.getPageNumber() == 1:
            _draw_score_card(canvas_obj, doc_ref, score_value, grade, accent)

    try:
        doc.build(story, onFirstPage=_on_page, onLaterPages=_on_page)
    except Exception:
        logger.exception("[PDF] Build failed for user_id=%s", user_id)
        return None, {"error": "build_failed"}

    pdf_bytes = buffer.getvalue()
    buffer.close()

    metadata = {
        "variant": variant,
        "score": int(round(score_value)),
        "grade": grade,
        "size_bytes": len(pdf_bytes),
    }
    return pdf_bytes, metadata


# ── Logging + rate limits ───────────────────────────────


def log_pdf_generation(user_id, tier, variant, score, size_bytes):
    """Insert a row into pdf_generations. Safe to call after every
    successful generation — failures to log should not block the
    user from downloading the PDF."""
    try:
        execute(
            "INSERT INTO pdf_generations "
            "(user_id, tier, variant, signal_score, file_size_bytes) "
            "VALUES (?, ?, ?, ?, ?)",
            (user_id, tier, variant, score, size_bytes),
        )
    except Exception:
        logger.exception("[PDF] Failed to log generation for user %s", user_id)


def count_pdfs_today(user_id):
    """How many PDFs this user has generated since UTC midnight.
    Used by the route handler to enforce daily limits from tiers.py."""
    try:
        row = fetchone(
            "SELECT COUNT(*) AS n FROM pdf_generations "
            "WHERE user_id = ? AND date(generated_at) = date('now')",
            (user_id,),
        )
        return row["n"] if row else 0
    except Exception:
        logger.exception("[PDF] count_pdfs_today failed")
        return 0
